// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3iOhpE0xgnYpmqcphyHh-9XNM7MWY_Jc',
    appId: '1:843102973143:android:7734d3a6ed4cadbf711492',
    messagingSenderId: '843102973143',
    projectId: 'loginwithusernamefirebase',
    databaseURL: 'https://loginwithusernamefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginwithusernamefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1DTcQXRKKmfxzj_gUIlvKhOl8Os_jjwU',
    appId: '1:843102973143:ios:917b44ffef15a36e711492',
    messagingSenderId: '843102973143',
    projectId: 'loginwithusernamefirebase',
    databaseURL: 'https://loginwithusernamefirebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'loginwithusernamefirebase.appspot.com',
    androidClientId: '843102973143-4p7oerh1lbgbbm5jd0d5l6ul08e41fqi.apps.googleusercontent.com',
    iosClientId: '843102973143-j809fvfp57eig9tdh83a69qiq4c0dqdk.apps.googleusercontent.com',
    iosBundleId: 'com.example.three',
  );
}
